name: barcode_scanner_example
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  barcode_widget: ^1.5.0
  cupertino_icons: ^1.0.0
  davinci: null
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^1.0.1
  get: ^4.6.1
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/.
